import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "MonoLisa-ExtraLight"

[font.bold_italic]
family = "MonoLisa-BoldItalic"
# style = "Bold Italic"

[font.italic]
family = "MonoLisa-Italic"
# style = "Italic"

[font.normal]
family = "MonoLisa-Medium"
# style = "Regular"
